// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("PdfGenerator")>]
[<assembly: AssemblyProductAttribute("Reconciliation")>]
[<assembly: AssemblyDescriptionAttribute("")>]
[<assembly: AssemblyVersionAttribute("4.0")>]
[<assembly: AssemblyFileVersionAttribute("4.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "PdfGenerator"
    let [<Literal>] AssemblyProduct = "Reconciliation"
    let [<Literal>] AssemblyDescription = ""
    let [<Literal>] AssemblyVersion = "4.0"
    let [<Literal>] AssemblyFileVersion = "4.0"
